apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    alpha.image.policy.openshift.io/resolve-names: "*"
    app.openshift.io/route-disabled: "false"
  labels:
    app: moveit-next-k8s
    app.kubernetes.io/component: moveit-next-k8s
    app.kubernetes.io/instance: moveit-next-k8s
    app.kubernetes.io/name: moveit-next-k8s
    app.kubernetes.io/part-of: moveit-next-app
    app.openshift.io/runtime: moveit-next
  name: moveit-next-k8s
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: moveit-next
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: moveit-next-k8s
        deployment: moveit-next-k8s
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: moveit-next-k8s
          image: quay.io/cleitonm/moveit-next:latest
          ports:
            - containerPort: 3000
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
