kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: 'yes'
    pv.kubernetes.io/bound-by-controller: 'yes'
    volume.beta.kubernetes.io/storage-provisioner: openshift-storage.rbd.csi.ceph.com
    volume.kubernetes.io/storage-provisioner: openshift-storage.rbd.csi.ceph.com
  resourceVersion: '724129'
  name: ClaimPV
  uid: 26fc70e0-60b4-4bfb-8df4-1563b610658c
  creationTimestamp: '2023-12-26T22:10:32Z'
  managedFields:
    - manager: Go-http-client
      operation: Update
      apiVersion: v1
    - manager: kube-controller-manager
      operation: Update
      apiVersion: v1
      time: '2023-12-26T22:10:32Z'
      fieldsType: FieldsV1
     
    - manager: kube-controller-manager
      operation: Update
      apiVersion: v1
      
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:accessModes': {}
          'f:capacity':
            .: {}
            'f:storage': {}
          'f:phase': {}
      subresource: status
  namespace: moveit
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: mypvc
  storageClassName: ocs-storagecluster-ceph-rbd
  volumeMode: Filesystem
status:
  phase: Bound
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi