apiVersion: v1
kind: Service
metadata:
  labels:
    app: moveit-next-k8s
    app.kubernetes.io/component: moveit-next-k8s
    app.kubernetes.io/instance: moveit-next-k8s
    app.kubernetes.io/name: moveit-next-k8s
    app.kubernetes.io/part-of: moveit-next
    app.openshift.io/runtime-version: latest
  name: moveit-next-k8s
spec:
  internalTrafficPolicy: Cluster
  ports:
    - name: 3000-tcp
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: moveit-next-k8s
    deployment: moveit-next-k8s
  sessionAffinity: None
  type: ClusterIP
